name: deploy

on:
  push:
    branches: [main]
  pull_request:

jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Terragrunt plan - Kumetynas
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        uses: the-commons-project/terragrunt-github-actions@1.0.6
        with:
          tf_actions_subcommand: plan-all
          tf_actions_version: 0.13.5
          tf_actions_working_dir: megadodo/eu-north-1/production

  deploy:
    runs-on: ubuntu-latest
    environment:
      name: production
    if: github.event_name == 'push'
    needs: plan
    steps:
      - uses: actions/checkout@v2
      - name: Terragrunt apply - Kumetynas
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        uses: the-commons-project/terragrunt-github-actions@1.0.6
        with:
          tf_actions_subcommand: apply-all
          tf_actions_version: 0.13.5
          tf_actions_working_dir: megadodo/eu-north-1/production
