name: deploy

on:
  push:
    branches: [main]
  pull_request:

jobs:
  plan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Terragrunt
        uses: autero1/action-terragrunt@v1.0.0
        with:
          terragrunt_version: 0.28.2
      - name: Terragrunt plan-all - Kumetynas
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          GIT_SSH_COMMAND: "echo '${{ secrets.INFRASTRUCTURE_MODULES_DEPLOY_KEY }}' > id_rsa
                  && ssh-keyscan github.com > known_hosts
                  && chmod 600 id_rsa known_hosts
                  && ssh -i ./id_rsa -o UserKnownHostsFile=./known_hosts"
        working-directory: megadodo/eu-north-1/production/kumetynas
        run: terragrunt run-all plan --terragrunt-non-interactive

  deploy:
    runs-on: ubuntu-latest
    environment:
      name: production
    if: github.event_name == 'push'
    needs: plan
    steps:
      - uses: actions/checkout@v2
      - name: Setup Terragrunt
        uses: autero1/action-terragrunt@v1.0.0
        with:
          terragrunt_version: 0.28.2
      - name: Terragrunt apply-all - Kumetynas
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          GIT_SSH_COMMAND: "echo '${{ secrets.INFRASTRUCTURE_MODULES_DEPLOY_KEY }}' > id_rsa
                  && ssh-keyscan github.com > known_hosts
                  && chmod 600 id_rsa known_hosts
                  && ssh -i ./id_rsa -o UserKnownHostsFile=./known_hosts"
        working-directory: megadodo/eu-north-1/production/kumetynas
        run: terragrunt run-all apply --terragrunt-non-interactive
